#=============================================================================================== 核心配置
#=============================================================================================== 数据库配置
#=============================================================================================== 日志配置
logging:
  config: classpath:logback-sdk.xml      #指定logback日志文件（默认logback-spring.xml）
  level:
    root: info
    org.mybatis: debug
    java.sql: debug
    org.springframework.web: debug